### PR TITLE
Normalize default metrics

### PR DESCRIPTION
**Pull request by phnx47**
Rename metrics:

```sh
process_virtual_bytes -> process_virtual_memory_bytes
process_private_bytes -> process_private_memory_bytes
process_working_set -> process_working_set_bytes
dotnet_totalmemory -> dotnet_total_memory_bytes
```
Add metrics:

```sh
process_open_handles
```

Should be compatible with https://grafana.com/grafana/dashboards/10427

### CODE REVIEW

**Comment by phnx47** [comment]
I'm not sure about `process_processid`, maybe better rename it to `process_id`...

**Comment by sanych-sun** [comment]
"fds" - is it count of open file descriptors? If so, not sure if it's possible without pinvoke.

**Comment by phnx47** [comment]
`process_open_fds` - Number of open file descriptors
`process_max_fds` - Maximum number of open file descriptors
`process_resident_memory_bytes` - Resident memory size in bytes

I found these metrics in Go and Java client

**Comment by phnx47** [comment]
I will come back to this task soon

**Pull request merged**
